// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SiLadhida.API.Data;

#nullable disable

namespace SiLadhida.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260504172408_RemoveNamaKue")]
    partial class RemoveNamaKue
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SiLadhida.Core.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Harga")
                        .HasColumnType("int");

                    b.Property<int>("PesananId")
                        .HasColumnType("int");

                    b.Property<int>("ProdukId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PesananId");

                    b.HasIndex("ProdukId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("SiLadhida.Core.Entities.Pesanan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NamaPemesan")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("StatusSekarang")
                        .HasColumnType("int");

                    b.Property<int>("TotalHarga")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Pesanan");
                });

            modelBuilder.Entity("SiLadhida.Core.Entities.Produk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Harga")
                        .HasColumnType("int");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Produk");
                });

            modelBuilder.Entity("SiLadhida.Core.Entities.OrderItem", b =>
                {
                    b.HasOne("SiLadhida.Core.Entities.Pesanan", "Pesanan")
                        .WithMany("Items")
                        .HasForeignKey("PesananId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SiLadhida.Core.Entities.Produk", "Produk")
                        .WithMany()
                        .HasForeignKey("ProdukId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pesanan");

                    b.Navigation("Produk");
                });

            modelBuilder.Entity("SiLadhida.Core.Entities.Pesanan", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
