// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SiLadhida.API.Data;

#nullable disable

namespace SiLadhida.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260610073723_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SiLadhida.Core.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("NamaPemesan")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("StatusSekarang")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalHarga")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("SiLadhida.Core.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("Harga")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("SiLadhida.Core.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("Harga")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Harga = 18000m,
                            Nama = "Bolu Coklat",
                            Stock = 50
                        },
                        new
                        {
                            Id = 2,
                            Harga = 25000m,
                            Nama = "Bolu Strawberry",
                            Stock = 40
                        },
                        new
                        {
                            Id = 3,
                            Harga = 28000m,
                            Nama = "Bolu Pandan",
                            Stock = 35
                        },
                        new
                        {
                            Id = 4,
                            Harga = 22000m,
                            Nama = "Bolu Keju",
                            Stock = 60
                        },
                        new
                        {
                            Id = 5,
                            Harga = 15000m,
                            Nama = "Bolu Coklat Keju",
                            Stock = 25
                        },
                        new
                        {
                            Id = 6,
                            Harga = 15000m,
                            Nama = "Bolu Keju Pandan",
                            Stock = 25
                        },
                        new
                        {
                            Id = 7,
                            Harga = 15000m,
                            Nama = "Bolu Coklat Strawberry",
                            Stock = 25
                        },
                        new
                        {
                            Id = 8,
                            Harga = 15000m,
                            Nama = "Nastar",
                            Stock = 25
                        },
                        new
                        {
                            Id = 9,
                            Harga = 15000m,
                            Nama = "Kastengel",
                            Stock = 25
                        },
                        new
                        {
                            Id = 10,
                            Harga = 15000m,
                            Nama = "Kue Sagu Keju",
                            Stock = 25
                        },
                        new
                        {
                            Id = 11,
                            Harga = 15000m,
                            Nama = "Kue Rambutan Coklat",
                            Stock = 25
                        });
                });

            modelBuilder.Entity("SiLadhida.Core.Entities.OrderItem", b =>
                {
                    b.HasOne("SiLadhida.Core.Entities.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SiLadhida.Core.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SiLadhida.Core.Entities.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
