// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SiLadhida.API.Data;

#nullable disable

namespace SiLadhida.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SiLadhida.Core.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("Harga")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("PesananId")
                        .HasColumnType("int");

                    b.Property<int>("ProdukId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PesananId");

                    b.HasIndex("ProdukId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("SiLadhida.Core.Entities.Pesanan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("NamaPemesan")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("StatusSekarang")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalHarga")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("Pesanan");
                });

            modelBuilder.Entity("SiLadhida.Core.Entities.Produk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("Harga")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Produk");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Harga = 18000m,
                            Nama = "Espresso",
                            Stock = 50
                        },
                        new
                        {
                            Id = 2,
                            Harga = 25000m,
                            Nama = "Cappuccino",
                            Stock = 40
                        },
                        new
                        {
                            Id = 3,
                            Harga = 28000m,
                            Nama = "Latte",
                            Stock = 35
                        },
                        new
                        {
                            Id = 4,
                            Harga = 22000m,
                            Nama = "Americano",
                            Stock = 60
                        },
                        new
                        {
                            Id = 5,
                            Harga = 15000m,
                            Nama = "Croissant",
                            Stock = 25
                        });
                });

            modelBuilder.Entity("SiLadhida.Core.Entities.OrderItem", b =>
                {
                    b.HasOne("SiLadhida.Core.Entities.Pesanan", "Pesanan")
                        .WithMany("Items")
                        .HasForeignKey("PesananId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SiLadhida.Core.Entities.Produk", "Produk")
                        .WithMany()
                        .HasForeignKey("ProdukId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pesanan");

                    b.Navigation("Produk");
                });

            modelBuilder.Entity("SiLadhida.Core.Entities.Pesanan", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
